# Generated by Django 2.2 on 2022-07-15 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminDashboardApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empRole', to='adminDashboardApp.Role')),
                ('emp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
