# Generated by Django 2.2 on 2022-07-15 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminDashboardApp', '0002_employeerole_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserRoles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=500)),
                ('roles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='auth.Permission')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
