# Generated by Django 2.2 on 2022-07-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboardApp', '0005_auto_20220726_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('hr', 'Hr'), ('backoffice', 'Backoffice'), ('developer', 'Developer'), ('designer', 'Designer'), ('business_development', 'Business_Development'), ('admin', 'Admin')], default='hr', max_length=250),
        ),
    ]
