# Generated by Django 4.0.6 on 2022-07-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboardApp', '0006_auto_20220726_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_topic', models.CharField(max_length=255)),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.TimeField()),
                ('meeting_duration', models.CharField(max_length=100)),
                ('meeting_users', models.CharField(max_length=555)),
                ('meeting_with_staff', models.CharField(max_length=555)),
                ('meeting_zoom_link', models.CharField(max_length=600)),
                ('meeting_zoom_password', models.CharField(max_length=255)),
            ],
        ),
    ]
