# Generated by Django 4.0.6 on 2022-07-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboardApp', '0007_zoommeetings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoommeetings',
            name='meeting_users',
        ),
        migrations.RemoveField(
            model_name='zoommeetings',
            name='meeting_with_staff',
        ),
    ]
