# Generated by Django 4.0.6 on 2022-07-27 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboardApp', '0008_remove_zoommeetings_meeting_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeetingsUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=555, null=True)),
                ('users_staff', models.CharField(max_length=555, null=True)),
                ('zoom_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminDashboardApp.zoommeetings')),
            ],
        ),
    ]
