# Generated by Django 4.0.6 on 2022-07-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboardApp', '0009_zoommeetingsusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoommeetings',
            name='meeting_zoom_link',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='zoommeetings',
            name='meeting_zoom_password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
