# Generated by Django 4.0.6 on 2022-07-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboardApp', '0012_zoommeetingsusers_mail_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeetingsusers',
            name='message',
            field=models.CharField(max_length=355, null=True),
        ),
    ]
