# Generated by Django 4.0.6 on 2022-08-01 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminDashboardApp', '0013_zoommeetingsusers_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobUsersProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='job_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes')),
                ('higer_secondary_year', models.IntegerField(blank=True)),
                ('secondary_year', models.IntegerField(blank=True)),
                ('grad_year', models.IntegerField(blank=True)),
                ('post_grad_year', models.IntegerField(blank=True)),
                ('looking_for', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Remote', 'Remote')], default='Full Time', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
