# Generated by Django 4.0.6 on 2022-08-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboardApp', '0014_jobusersprofile_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.DeleteModel(
            name='JobUsersProfile',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
