from django.urls import path
from adminDashboardApp import views

app_name = 'adminDashboardApp'

urlpatterns = [
    path('', views.adminDashboard, name="dashboard"),
    path('pdf/', views.test, name="test"),
    path('createNewUser/', views.employeeRegisterUser, name='createNewUser'),
    path('employeePersonal/<int:pk>/', views.employeePersonalDetail,
         name='employeePersonalDetail'),
    path('listEmployee/', views.employeeDetailList, name="employee_list"),
    path('listAdmin/', views.adminDetailList, name="admin_list"),
    path('createRole/',
         views.createRoleAdmin.as_view(), name="createRole"),
    path('roleUpdate/<slug:slug>',
         views.roleUpdateView.as_view(), name="roleUpdate"),
    path('deleteRole/<slug:slug>',
         views.deleteAdminUserRoles.as_view(), name="deleteRole"),
    path('convertToAdmin/<int:pk>',
         views.convertNormalUserToAdmin, name="convertToAdmin"),
    path('convertToNormal/<int:pk>',
         views.convertAdminToNormal, name="convertToNormal"),
    path('deleteUser/<int:pk>/<str:nm>',
         views.deactivatedUserByAdmin, name="deleteUser"),
    path('deactivatedUsers/',
         views.deactivatedUsers, name="deactivatedUsers"),
    path('activatedUsers/<int:pk>',
         views.activatedUsers, name="activatedUsers"),
    path('deleteDeactivatedUser/<int:pk>',
         views.deleteDeactivatedUser.as_view(), name="deleteDeactivatedUser"),
    #path('attendance/', views.AttendanceRecord.as_view(), name="attendance"),
    path('attendance/', views.attendance, name="attendance"),
    path('joinLetter/', views.joinLetter, name="joinLetter"),
    path('converted_pdf/', views.convertPdf, name='converted_pdf'),

    path('zoom_meeting/', views.zoomMeeting, name='zoom_meeting'),
    path('zoom_meeting_create/', views.zoomMeetingCreateView.as_view(),
         name='zoom_meeting_create'),
    path('zoom_meeting_user_create/<int:pk>', views.zoomMeetingUsersCreateView.as_view(),
         name='zoom_meeting_user_create'),
    path('zoom_meeting_list/', views.zoomMeetingListView.as_view(),
         name='zoom_meeting_list'),
    path('zoom_meeting_user_details/<int:pk>', views.zoomMeetingDetailView.as_view(),
         name='zoom_meeting_user_detail'),
    path('zoom_meeting_Delete/<int:pk>', views.zoomMeetingDeleteView.as_view(),
         name='zoom_meeting_Delete'),
    path('zoom_meeting_send_mail/<int:pk>', views.zoomMeetingSendMailView.as_view(),
         name='zoom_meeting_send_mail'),
    path('organisation/', views.organisationView.as_view(),
         name='organisation_detail'),

    path('department/', views.departmentListView.as_view(),
         name="department"),
    path('departmentcreate/', views.departmentCreateView.as_view(),
         name="department_create"),
    path('departmentupdate/<int:pk>', views.departmentUpdateView.as_view(),
         name="department_update"),
    path('departmentdelete/<int:pk>', views.departmentDeleteView.as_view(),
         name="department_delete"),
]
